### ISSUE TITLE
Login process should not give a clue about wrong password

### ISSUE THREAD

**Issue by frayaIzv** [svlazz/urtltopdf#2]
https://github.com/svlazz/urtltopdf/blob/42d62a15dadf8dd0b9d0bf893f7631cd239b17b4/web/login.php#L28

See https://stackoverflow.com/questions/14922130/which-error-message-is-better-when-users-entered-a-wrong-password

It's better to use the same message error for both: wrong username and wrong password.

**Comment by svlazz** [comment]
changed, now shows both "usuario o contraseña equivocada"
